# Generated by Django 3.1.5 on 2021-01-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210124_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
