# Generated by Django 3.1.5 on 2021-01-27 02:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210125_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watch',
            field=models.ManyToManyField(blank=True, related_name='listing_watch', to=settings.AUTH_USER_MODEL),
        ),
    ]
